import {describe, expect, test} from '@jest/globals';
import {start} from './index';

describe('parse module', () => {
  test('parse self dependency', () => {
    expect(start(undefined)).toStrictEqual({"count": 17, "hasCircularDependency": false, "map": {"ansi-regex": {"circular": false, "dependencies": {}, "requiredTimes": 1, "version": "^5.0.1"}, "ansi-styles": {"circular": false, "dependencies": {"color-convert": "^2.0.1"}, "requiredTimes": 1, "version": "^4.0.0"}, "cliui": {"circular": false, "dependencies": {"string-width": "^4.2.0", "strip-ansi": "^6.0.1", "wrap-ansi": "^7.0.0"}, "requiredTimes": 1, "version": "^8.0.1"}, "color-convert": {"circular": false, "dependencies": {"color-name": "~1.1.4"}, "requiredTimes": 1, "version": "^2.0.1"}, "color-name": {"circular": false, "dependencies": {}, "requiredTimes": 1, "version": "~1.1.4"}, "emoji-regex": {"circular": false, "dependencies": {}, "requiredTimes": 1, "version": "^8.0.0"}, "escalade": {"circular": false, "dependencies": {}, "requiredTimes": 1, "version": "^3.1.1"}, "get-caller-file": {"circular": false, "dependencies": {}, "requiredTimes": 1, "version": "^2.0.5"}, "getdep": {"circular": false, "dependencies": {"yargs": "^17.7.2"}, "requiredTimes": 0, "version": "1.0.0"}, "is-fullwidth-code-point": {"circular": false, "dependencies": {}, "requiredTimes": 1, "version": "^3.0.0"}, "require-directory": {"circular": false, "dependencies": {}, "requiredTimes": 1, "version": "^2.1.1"}, "string-width": {"circular": false, "dependencies": {"emoji-regex": "^8.0.0", "is-fullwidth-code-point": "^3.0.0", "strip-ansi": "^6.0.1"}, "requiredTimes": 1, "version": "^4.2.0"}, "strip-ansi": {"circular": false, "dependencies": {"ansi-regex": "^5.0.1"}, "requiredTimes": 2, "version": "^6.0.1"}, "wrap-ansi": {"circular": false, "dependencies": {"ansi-styles": "^4.0.0", "string-width": "^4.1.0", "strip-ansi": "^6.0.0"}, "requiredTimes": 1, "version": "^7.0.0"}, "y18n": {"circular": false, "dependencies": {}, "requiredTimes": 1, "version": "^5.0.5"}, "yargs": {"circular": false, "dependencies": {"cliui": "^8.0.1", "escalade": "^3.1.1", "get-caller-file": "^2.0.5", "require-directory": "^2.1.1", "string-width": "^4.2.3", "y18n": "^5.0.5", "yargs-parser": "^21.1.1"}, "requiredTimes": 1, "version": "^17.7.2"}, "yargs-parser": {"circular": false, "dependencies": {}, "requiredTimes": 1, "version": "^21.1.1"}}, "name": "getdep", "version": "1.0.0"});
  });
    test('parse circular dependency', () => {
    expect(start(undefined,'./test/circular/')).toStrictEqual({"count": 2,"hasCircularDependency": false,"map": {"circular-test": {"circular": false,"dependencies": {"circular-test-a": "0",},"requiredTimes": 0,"version": "1.0.0",},"circular-test-a": {"circular": false,"dependencies": {},"requiredTimes": 1,"version": "0",},},"name": "circular-test","version": "1.0.0",});
  });
});